apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::417762401845:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1V2HDPL93E61F
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::417762401845:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-27T19:17:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1585"
  uid: fc9a6b88-50d2-4411-9248-111f3d99fbc4
